### ISSUE TITLE
doesn't handle concurrent write like mattn go-sqlite

### ISSUE THREAD

**Issue by kamalshkeir** [glebarez/go-sqlite#89]
[ERROR] main.main.func1 [line:30] : database is locked (5) (SQLITE_BUSY)
 [ERROR] main.main.func1 [line:30] : database is locked (5) (SQLITE_BUSY)
 [ERROR] main.main.func1 [line:30] : database is locked (5) (SQLITE_BUSY)
 [ERROR] main.main.func1 [line:30] : database is locked (5) (SQLITE_BUSY)
 
 Example :
 
 ```go
 package main

import (
	"fmt"
	"strconv"

	_ "github.com/glebarez/go-sqlite"
	"github.com/kamalshkeir/klog"
	"github.com/kamalshkeir/korm"
)

func main() {
	err := korm.New(korm.SQLITE, "db")
	if klog.CheckError(err) {
		return
	}
	defer korm.Shutdown()

	srv := korm.WithDashboard()
	korm.WithShell()

	for i := 0; i < 5; i++ {
		go func(i int) {
			iStr := strconv.Itoa(i)
			users, err := korm.Model[korm.User]().Insert(&korm.User{
				Uuid:     iStr + "-uuid",
				Email:    "email-" + iStr + "@gmail.com",
				Password: "somepass",
			})
			if !klog.CheckError(err) {
				fmt.Println(users)
			}
		}(i)
	}

	srv.Run("localhost:9313")
}

 ```

**Comment by glebarez** [comment]
Hello, this behaviour is intended by sqlite.
mattn's driver sidesteps this by silently setting ```BUSY_TIMEOUT``` pragma to ```5000```.
(see https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L1084)
You can achieve the same effect adding parameter to connection string, e.g.:
```
path/to/some.db?_pragma=busy_timeout(5000)
```

**Comment by kamalshkeir** [comment]
> Hello, this behaviour is intended by sqlite.
> mattn's driver sidesteps this by silently setting ```BUSY_TIMEOUT``` pragma to ```5000```.
> (see https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L1084)
> You can achieve the same effect adding parameter to connection string, e.g.:
> ```
> path/to/some.db?_pragma=busy_timeout(5000)
> ```

Thank you

**Comment by pplmx** [comment]
I set it by `path/to/some.db?_pragma=busy_timeout(5000)`, but it doesn't work and still throw the busy error

**Comment by hyl00** [comment]
> I set it by `path/to/some.db?_pragma=busy_timeout(5000)`, but it doesn't work and still throw the busy error

Hello, I encountered the same problem, did you solve it?

**Comment by pplmx** [comment]
@hyl00 I limit the connection. Like this:

```go
	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)
	db.SetConnMaxLifetime(time.Hour)
```

**Comment by kamalshkeir** [comment]
@hyl00 it worked like this:

on init connection, after ping, you execute this query:

```sql
PRAGMA busy_timeout = 5000;
```
