### ISSUE TITLE
panic: sql: Register called twice for driver sqlite

### ISSUE THREAD

**Issue by DevHaoZi** [glebarez/go-sqlite#97]
I used both [https://github.com/golang-migrate/migrate/blob/master/database/sqlite/sqlite.go](https://github.com/golang-migrate/migrate/blob/master/database/sqlite/sqlite.go) and [https://github.com/glebarez/sqlite](https://github.com/glebarez/sqlite), and this error occurred.

```
panic: sql: Register called twice for driver sqlite

goroutine 1 [running]:
database/sql.Register({0x100dc4183, 0x6}, {0x10123a760, 0x1019d67c8})
        /Users/haozi/go/go1.20/src/database/sql/sql.go:51 +0x124
modernc.org/sqlite.init.0()
        /Users/haozi/go/pkg/mod/modernc.org/sqlite@v1.21.1/sqlite.go:122 +0x38
FAIL    app/database   4.525s
panic: sql: Register called twice for driver sqlite

goroutine 1 [running]:
database/sql.Register({0x10389d1c6, 0x6}, {0x103d083a0, 0x104470b38})
        /Users/haozi/go/go1.20/src/database/sql/sql.go:51 +0x124
github.com/glebarez/go-sqlite.init.0()
        /Users/haozi/go/pkg/mod/github.com/glebarez/go-sqlite@v1.21.1/sqlite.go:126 +0x38
FAIL    app/database/console   3.814s
```

**Comment by DevHaoZi** [comment]
Can't use `replace`, the two package structures are not exactly the same.

**Comment by glebarez** [comment]
Are you using GORM ?

**Comment by DevHaoZi** [comment]
> Are you using GORM ?

Yes

**Comment by DevHaoZi** [comment]
Maybe a new driver needs to be added for [https://github.com/golang-migrate/migrate](https://github.com/golang-migrate/migrate), what do you think?

**Comment by glebarez** [comment]
The cause is really registration of both drivers under same name.
I don't think adding ```go-sqlite``` drivers to migrate package is the right way.

I think more elegant would be to avoid importing GORM driver at time of migration.
E.g. make it separate package.
